services:
  db:
    build: ./db
    container_name: my-db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: student_tracker
      TZ: UTC
    ports:
      - "5432:5432"
    

volumes:
  postgres_data: