spring.application.name=demo-spring-boot

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_directory
spring.datasource.username=user
spring.datasource.password=pass

spring.main.banner-mode=off
logging.level.root=warn

logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace