spring.application.name=demospringboot

# PostgreSQL Database Connection Settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/student_tracker
spring.datasource.username=user
spring.datasource.password=pass

# Turn off the default Spring Boot banner
spring.main.banner-mode=off

# Reduce logging level. Set logging level to warn
logging.level.root=warn

# Add logging configs to display SQL statements and their parameters
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# Config for Hibernate to automatically create/update the database schema based on the entity classes
spring.jpa.hibernate.ddl-auto=update