spring.application.name=demo-spring-boot

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_directory
spring.datasource.username=user
spring.datasource.password=pass

spring.data.rest.base-path=/api
spring.data.rest.default-page-size=3

spring.security.user.name=user
spring.security.user.password=password

logging.level.org.springframework.security=DEBUG