DROP SCHEMA IF EXISTS "hb-01-one-to-one-uni" CASCADE;

CREATE SCHEMA "hb-01-one-to-one-uni";

SET search_path TO "hb-01-one-to-one-uni";

CREATE TABLE instructor_detail (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    youtube_channel VARCHAR(128),
    hobby VARCHAR(45)
);

CREATE TABLE instructor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(45),
    last_name VARCHAR(45),
    email VARCHAR(45),
    instructor_detail_id INTEGER,
    
    CONSTRAINT fk_detail
        FOREIGN KEY (instructor_detail_id)
        REFERENCES instructor_detail(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);