CREATE TABLE course (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) DEFAULT NULL,
    instructor_id INTEGER DEFAULT NULL,

    CONSTRAINT title_unique UNIQUE (title),

    CONSTRAINT fk_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES instructor (id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);