CREATE TABLE review (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    comment VARCHAR(256) DEFAULT NULL,
    course_id INTEGER DEFAULT NULL,

    PRIMARY KEY (id),

    CONSTRAINT fk_course
        FOREIGN KEY (course_id)
        REFERENCES course (id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE INDEX fk_course_id_idx
    ON review (course_id);